services:
  - type: web
    name: gpt-invest-news-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your-telegram-bot-token
      - key: OPENAI_API_KEY
        value: your-openai-api-key