services:
  - type: web
    name: gpt-invest-news-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    autoDeploy: true
    startServiceTimeoutSeconds: 0
    envVars:
      - key: OPENAI_API_KEY
        value: your_openai_key
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token
